# Generated by Django 4.1.7 on 2023-06-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hotplist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True)),
                ('original_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[hotplist.models.validate_rating])),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[hotplist.models.validate_rating])),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotplist.hotplaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('pub_date', models.DateTimeField()),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotplist.hotplaces')),
            ],
        ),
    ]
