# Generated by Django 4.2 on 2023-05-31 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hotplist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=1, validators=[hotplist.models.validate_rating])),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='WantList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotplist.hotplaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1, validators=[hotplist.models.validate_rating])),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotplist.hotplaces')),
            ],
        ),
    ]
