# Generated by Django 4.1.7 on 2023-06-21 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotplist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplaces',
            name='like_users',
            field=models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SavedPlaces',
        ),
    ]
