# Generated by Django 4.2.1 on 2023-05-30 13:16

from django.db import migrations, models
import hotplist.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotplist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplaces',
            name='original_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[hotplist.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='hotplaces',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[hotplist.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[hotplist.models.validate_rating]),
        ),
    ]
