# Generated by Django 4.2.1 on 2023-05-30 13:17

from django.db import migrations, models
import hotplist.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotplist', '0002_hotplaces_original_rating_alter_hotplaces_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplaces',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[hotplist.models.validate_rating]),
        ),
    ]
