# Generated by Django 4.2.1 on 2023-06-19 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotplist', '0003_alter_hotplaces_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplaces',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
