# Generated by Django 4.2 on 2023-06-23 07:55

from django.db import migrations, models
import hotplist.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotplist', '0003_hotplaces_origin_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplaces',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, null=True, validators=[hotplist.models.validate_rating]),
        ),
    ]
